fix(segmentedcontrol) color and selectors
Kong/kongponents pull request #263
Opened 2020-10-16 09:51 UTC by jackkav

### Summary
Before:
![image](https://user-images.githubusercontent.com/3679927/96243392-fbe3de00-0fa4-11eb-8540-d99bf9b658fe.png)

After:
![image](https://user-images.githubusercontent.com/3679927/96243301-d9ea5b80-0fa4-11eb-8d64-1314fa5cb369.png)

#### Changes made:
* mute colors to suit konnect design
* fix hover active and focus borders and box shadows

### PR Checklist
- [ ] Does not introduce dependencies
- [ ] **Functional:** all changes do not break existing APIs and if so, bump major version.
- [ ] **Tests pass:** check the output of yarn test packages/<Kongponent>
- [ ] **Naming:** the files and the method and prop variables use the same naming conventions as other Kongponents
- [ ] **Framework style:** abides by the essential rules in Vue's style guide
- [ ] **Cleanliness:** does not have formatting issues, unused code (e.g., console.logs), or leftover comments
- [ ] **Docs:** includes a technically accurate README, uses JSDOC where appropriate

2020-10-16 17:58 UTC, travispamaral requested changes

2020-10-16 17:58 UTC, travispamaral commented on packages/KSegmentedControl/KSegmentedControl.vue
> +  --KButtonPrimaryBase: var(--blue-100);
Let's move these to the top of block. And then lets use a new var with a fallback of blue-600 and import the vars so like in other kongponents.

```scss
@import '~@kongponents/styles/_variables.scss';

.segmented-control .k-button {
--KButtonPrimaryBase: var(--blue-100);
--KButtonPrimaryHover: var(--blue-100);

color: var(--KSegementedControlPrimary, var(--blue-600, color(blue-600)));
```

2020-10-16 17:58 UTC, travispamaral commented on packages/KSegmentedControl/KSegmentedControl.vue
> +    border-color: var(--blue-600);
these can all be the same zindex too I think

2020-10-16 17:58 UTC, travispamaral commented on packages/KSegmentedControl/KSegmentedControl.vue
> +    border-color: var(--blue-600);
```suggestion
```

2020-10-19 13:29 UTC, jackkav commented
focus is z-index 3 to avoid this case 
![image](https://user-images.githubusercontent.com/3679927/96457265-d6aed400-121f-11eb-9f0c-7508da7c136b.png)

2020-10-19 16:34 UTC, merged