style(KCheckbox,KRadio): add margin-right to input
Kong/kongponents pull request #294
Opened 2021-04-09 04:55 UTC by dustinryerson

### Summary
This adds consistent margin between input and label for checkboxes and radios

#### Changes made:
* Added `margin-right: 4px` to KRadio input
* Added `margin-right: 8px` to KCheckbox input

### PR Checklist
- [x] Does not introduce dependencies
- [x] **Functional:** all changes do not break existing APIs and if so, bump major version.
- [x] **Tests pass:** check the output of yarn test packages/<Kongponent>
- [x] **Naming:** the files and the method and prop variables use the same naming conventions as other Kongponents
- [x] **Framework style:** abides by the essential rules in Vue's style guide
- [x] **Cleanliness:** does not have formatting issues, unused code (e.g., console.logs), or leftover comments
- [x] **Docs:** includes a technically accurate README, uses JSDOC where appropriate

2021-04-09 15:48 UTC, kaiarrowood commented
We need to update the docs for checkboxes to have `margin-right`.

![image](https://user-images.githubusercontent.com/67973710/114206488-64df5980-9929-11eb-8410-92a18dd830b2.png)

While we are in here modifying radio buttons, can we fix the vertical alignment of the radio button text to be centered?

![image](https://user-images.githubusercontent.com/67973710/114206644-8c362680-9929-11eb-9846-68aa32f4fd0f.png)

2021-04-09 15:49 UTC, kaiarrowood requested changes
Address docs page stylling and radio button text alignment

2021-04-14 00:17 UTC, dustinryerson commented
Checkbox inputs now have the margin-right requested:
![Screen Shot 2021-04-13 at 4 46 17 PM](https://user-images.githubusercontent.com/2080476/114636495-07764000-9c7c-11eb-8b9b-f9cfc21ba72b.png)

Radio inputs are now aligned (by explicitly setting margins, overriding the margin that was causing the misalignment):
![Screen Shot 2021-04-13 at 5 04 51 PM](https://user-images.githubusercontent.com/2080476/114636528-1957e300-9c7c-11eb-958b-4607eded59eb.png)

2021-04-14 16:24 UTC, kaiarrowood approved these changes
Much better! ✨

2021-04-14 17:57 UTC, merged